# Site settings
title: Kehäsähkö
email: toni.ahola@kehasahko.fi
description: "Kehäsähkö on pääkaupunkiseudulla toimiva sähköalan yritys jonka valttina on joustava, edullinen ja nopea palvelu sähkötöille, myös iltaisin ja viikonloppuisin. Kaikki työmme ovat kotitalousvähennyskelpoisia."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 11826c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/kehasahko

# Postal address (add as many lines as necessary)
address:
  - line: Lehdespolku 5 E 32
  - line: 01360 VANTAA

# Build settings
markdown: kramdown
permalink: pretty
